Portfolio.components.services = () => `
<section id="services" class="section services-section"><div class="container"><div class="section-heading centered"><span class="eyebrow">필요한 순간에, 필요한 도구를</span><h2>함께 만들 수 있는 것들<span class="heading-dot">.</span></h2><div class="heading-line"></div><p>목적은 분명하게, 시작은 가볍게.<br>일상과 업무에 도움이 되는 결과물을 만듭니다.</p></div><div class="services-grid">${Portfolio.services.map(p=>`<article class="service-card"><span class="service-icon">${Portfolio.icon(p.icon)}</span><div><h3>${p.title}</h3><p>${p.copy}</p></div></article>`).join('')}</div></div></section>
<section class="section vision-section"><div class="container vision-grid"><div><span class="eyebrow">제가 바이브코딩을 하는 이유</span><h2>작은 불편에서 찾는 가능성<span class="heading-dot">.</span></h2><div class="heading-line"></div><p>좋은 서비스는 거창한 아이디어보다 일상에서 느끼는 작은 불편에서 시작한다고 생각합니다. 필요한 정보를 찾기 어렵거나, 같은 일을 반복하거나, 떠오른 생각을 시험해볼 방법이 없을 때 새로운 도구가 도움이 됩니다.</p><p>인공지능의 도움으로 빠르게 시작하고, 직접 사용해보며 완성도를 높입니다. 만들어진 코드와 화면을 확인하는 과정까지가 제가 생각하는 바이브코딩입니다.</p><ul class="check-list"><li>사용자와 목적을 먼저 이해하기</li><li>핵심 기능부터 작게 시작하기</li><li>직접 확인하고 꾸준히 개선하기</li></ul><span class="signature dark-signature">전용건</span></div><div class="vision-photo">${Portfolio.image('code','아이디어를 코드로 구현하는 작업 환경')}<span class="vision-seal">생각하고 <span>✦</span> 만들고 확인하기</span></div></div></section>
<section class="section solutions-section"><div class="container"><div class="section-heading centered"><span class="eyebrow">필요에 맞게 만드는 세 가지 방향</span><h2>어떤 고민이 있으신가요?<span class="heading-dot">.</span></h2><div class="heading-line"></div><p>아이디어가 아직 정리되지 않아도 괜찮습니다.<br>원하는 변화부터 함께 이야기합니다.</p></div><div class="solutions-grid">${[
{image:'laptop',title:'우리 브랜드를 소개하고 싶어요',copy:'첫 방문에서 신뢰를 주는 웹사이트를 생각하고 있나요?',items:['브랜드·서비스 소개 페이지','예약·문의로 이어지는 화면','모바일에서도 편한 구성']},
{image:'code',title:'반복 업무를 줄이고 싶어요',copy:'매번 손으로 하는 일을 더 간단하게 바꿔볼까요?',items:['문의와 업무 현황 정리','검색·필터·상태 관리 화면','반복 작업을 줄이는 도구']},
{image:'workspace',title:'아이디어를 시험해보고 싶어요',copy:'생각만 하던 서비스를 직접 써보는 형태로 만듭니다.',items:['핵심 기능 중심의 시제품','사용자 흐름과 화면 설계','반응을 확인하며 기능 개선']}
].map((p,i)=>`<article class="solution-card"><div class="solution-image">${Portfolio.image(p.image,p.title)}<span>0${i+1}</span></div><div class="solution-body"><h3>${p.title}</h3><p>${p.copy}</p><ul class="check-list">${p.items.map(item=>`<li>${item}</li>`).join('')}</ul><button class="text-link" data-contact>이런 작업 이야기하기 ${Portfolio.icon('arrow')}</button></div></article>`).join('')}</div></div></section>
<section id="process" class="section process-section"><div class="container"><div class="section-heading centered"><span class="eyebrow light">막연한 생각이 결과물이 되기까지</span><h2>이렇게 함께 작업합니다<span class="heading-dot">.</span></h2><div class="heading-line"></div><p>충분히 이해하고, 작게 만들어보고,<br>직접 확인하며 방향을 맞춥니다.</p></div><div class="process-grid">${[
{icon:'community',title:'이야기 나누기',period:'첫 번째 단계',copy:'누가 사용할지, 어떤 문제를 해결할지, 원하는 결과는 무엇인지 함께 정리합니다.'},
{icon:'education',title:'화면과 기능 정리',period:'두 번째 단계',copy:'필요한 화면과 핵심 기능을 고르고, 우선순위에 맞춰 작업 범위를 구체화합니다.'},
{icon:'growth',title:'만들고 확인하기',period:'세 번째 단계',copy:'인공지능을 활용해 구현하고, 실제 화면과 기능을 확인하며 수정을 이어갑니다.'},
{icon:'health',title:'다듬고 전달하기',period:'네 번째 단계',copy:'모바일 화면과 사용 흐름을 점검하고, 수정하기 편한 파일 구성으로 정리합니다.'}
].map((p,i)=>`<article class="process-card"><span class="process-number">0${i+1}</span>${Portfolio.icon(p.icon)}<h3>${p.title}</h3><span class="process-step">${p.period}</span><p>${p.copy}</p></article>`).join('')}</div></div></section>
<section class="section philosophy-section"><div class="container"><div class="section-heading centered"><span class="eyebrow">작업을 대하는 마음</span><h2>쓸모 있는 결과를 향해<span class="heading-dot">.</span></h2><div class="heading-line"></div></div><div class="philosophy">${Portfolio.icon('quote','quote-icon')}<blockquote>“빠르게 만드는 것에서 한 걸음 더.<br>실제로 쓰기 편한지 확인하고, 필요한 만큼 다듬는 사람이 되고 싶습니다.”</blockquote><div class="creator"><span class="creator-avatar" aria-hidden="true">전</span><div><strong>전용건</strong><span>서울 · 바이브코딩 제작자</span></div></div></div></div></section>`;
